sudo: required
language: python
python:
  - "3.6"

services:
- docker
env:
  global:
  - PATH="/usr/bin:$PATH"
  - secure: YC57dputfR71/AJdwUSSiY4it5QqGtvZxs6TOdpiIt4gfYG0W2q0gnCZgPtvLM+TuH8zgQXQjBoOrroS2xAtq6eciC9c0U6avSj7frMNXKTuUs6BQQM+DBQjiNq6N/sJcltygzTDu4fzsCU7mem++eykM/s2tyh17JVU/6Uzc6svzcWnyfKA4ydtD/09hYgMV8D6lJuXvIjjpdODUZ8M0T1/Ru9M7UfbD+O8ZOGV9EQqbaNkWX+yD8WmO22RcT/bAfu8g0h5CnA8I8yi3eyo7zuLKDdz4EVGKwqZDO/o5rFbbZ0lvi3m2urDuccxtYMWVL3h39v4izfkEfIf7w2mnmEOah82/NKjPMfso88yKu4gNMhX7o+qjJ7PFZ5w5Wde6sbM4n9e1syeVda99wZ/PFXjUY2ZyFw6dl+1Xya0CBo1yGcT5V7NwwZuEYKazfJ2OvAhXoa3lJctkVer7FN6A9kZ9BfFU7BO0gQOu7ycwe/ZB5sQFFQwNHaSS+kcu+3fBTdUMK6ZkVie/w/akr9hqk46b1Kd5SB8uDIho1lYvHSpKM8RNGRrPwSylt3/rqXJBnmG44YaNNDEg89HW1Stud+g1zWDV6+ZIAJS/8Uv79oB1ZMRNjSZxA/FE2g1a7vdkdAx7d2rLt4w1zQF73m//Sg21pHmIq75ANFS8j8UtV4=
  - DOCKER_USERNAME="rhmessagingqe"
before_install:
  # Docker-CE Installation
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
jobs:
  include:
  - stage: Build CentOS docker images
    script:
    - make all-centos all-alpine all-ubuntu all-debian brokers
    - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

    docker tag "$DOCKER_USERNAME"/sshd-service:centos7 rhmessagingqe/sshd-service:latest;
    docker push "$DOCKER_USERNAME"/sshd-service;

    docker tag "$DOCKER_USERNAME"/cli-rhea:alpine rhmessagingqe/cli-rhea:latest;
    docker push "$DOCKER_USERNAME"/cli-rhea;

    docker tag "$DOCKER_USERNAME"/cli-java:alpine rhmessagingqe/cli-java:latest;
    docker push "$DOCKER_USERNAME"/cli-java;

    docker tag "$DOCKER_USERNAME"/proton-lib:centos7 rhmessagingqe/proton-lib:latest;
    docker push "$DOCKER_USERNAME"/proton-lib;

    docker tag "$DOCKER_USERNAME"/cli-proton-python:centos7 rhmessagingqe/cli-proton-python:latest;
    docker push "$DOCKER_USERNAME"/cli-proton-python;

    docker tag "$DOCKER_USERNAME"/qpid-dispatch:centos7 rhmessagingqe/qpid-dispatch:latest;
    docker push "$DOCKER_USERNAME"/qpid-dispatch;

    docker tag "$DOCKER_USERNAME"/artemis:fedora27 rhmessagingqe/artemis:latest;
    docker push "$DOCKER_USERNAME"/artemis;

    fi
